//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_DODAEntities1 : DbContext
    {
        public DB_DODAEntities1()
            : base("name=DB_DODAEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_anhsanpham> tbl_anhsanpham { get; set; }
        public virtual DbSet<tbl_chitietdonhang> tbl_chitietdonhang { get; set; }
        public virtual DbSet<tbl_danhmucsanpham> tbl_danhmucsanpham { get; set; }
        public virtual DbSet<tbl_donhang> tbl_donhang { get; set; }
        public virtual DbSet<tbl_khachhang> tbl_khachhang { get; set; }
        public virtual DbSet<tbl_sanpham> tbl_sanpham { get; set; }
        public virtual DbSet<tbl_slide> tbl_slide { get; set; }
        public virtual DbSet<tbl_tintuc> tbl_tintuc { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
    }
}
