//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_anhsanpham
    {
        public System.Guid id_anhsanpham { get; set; }
        public System.Guid fk_sanpham { get; set; }
        public string c_image { get; set; }
    
        public virtual tbl_sanpham tbl_sanpham { get; set; }
    }
}
