//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tintuc
    {
        public System.Guid id_tintuc { get; set; }
        public string c_tieude { get; set; }
        public string c_mota { get; set; }
        public string c_chitiet { get; set; }
        public string c_image { get; set; }
    }
}
