//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_donhang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_donhang()
        {
            this.tbl_chitietdonhang = new HashSet<tbl_chitietdonhang>();
        }
    
        public System.Guid id_donhang { get; set; }
        public System.Guid fk_khachhang { get; set; }
        public System.DateTime c_ngaymua { get; set; }
        public float c_gia { get; set; }
        public bool c_trangthai { get; set; }
        public string c_ghichu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_chitietdonhang> tbl_chitietdonhang { get; set; }
        public virtual tbl_khachhang tbl_khachhang { get; set; }
    }
}
