//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_sanpham()
        {
            this.tbl_anhsanpham = new HashSet<tbl_anhsanpham>();
            this.tbl_chitietdonhang = new HashSet<tbl_chitietdonhang>();
        }
    
        public System.Guid id_sanpham { get; set; }
        public string c_tensanpham { get; set; }
        public System.Guid fk_danhmucsanpham { get; set; }
        public float c_gia { get; set; }
        public string c_thongtinchitiet { get; set; }
        public Nullable<bool> c_sanphamhot { get; set; }
        public Nullable<bool> c_sanphamkhuyenmai { get; set; }
        public int c_soluong { get; set; }
        public string c_mota { get; set; }
        public Nullable<System.DateTime> c_ngaytao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_anhsanpham> tbl_anhsanpham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_chitietdonhang> tbl_chitietdonhang { get; set; }
        public virtual tbl_danhmucsanpham tbl_danhmucsanpham { get; set; }
    }
}
