//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_slide
    {
        public System.Guid id_slide { get; set; }
        public string c_image1 { get; set; }
        public string c_image2 { get; set; }
        public string c_image3 { get; set; }
    }
}
